# DC schema
 
# --- !Ups

CREATE TABLE COMPANY (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  ADDRESS VARCHAR(255)
);

CREATE TABLE TEAM (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  COMPANY INTEGER NOT NULL,
  FOREIGN KEY (COMPANY) REFERENCES COMPANY (ID)
);

CREATE TABLE PROJECT (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE TASK (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COLOR VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PROJECT INTEGER NOT NULL,
    FOREIGN KEY (PROJECT) REFERENCES PROJECT (ID)
);

CREATE TABLE USER (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE MT_RESOURCE (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_KEY VARCHAR(255),
  RESOURCE_NAME VARCHAR(255)
);

CREATE TABLE MT_RESOURCE_DETAIL (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_TEXT VARCHAR(255),
  RESOURCE_LOCALE VARCHAR(255),
  RESOURCE_KEY INTEGER NOT NULL,
  FOREIGN KEY (RESOURCE_KEY) REFERENCES MT_RESOURCE (ID)
);
INSERT INTO MT_RESOURCE VALUES(1, 'default', '안녕하세요'), (2, 'default2', '윤창희 입니다.');
# --- !Downs
DROP TABLE COMPANY;
DROP TABLE TASK;
DROP TABLE PROJECT;
DROP TABLE TEAM;
DROP TABLE MT_RESOURCE;
DROP TABLE MT_RESOURCE_DETAIL;
DROP TABLE USER;

