# DC schema
 
# --- !Ups

CREATE TABLE USER (
  USERID VARCHAR(255) NOT NULL PRIMARY KEY,
  FIRSTNAME VARCHAR(255),
  LASTNAME VARCHAR(255),
  FULLNAME VARCHAR(255),
  EMAIL VARCHAR(255),
  AVATARURL VARCHAR(255)
);

CREATE TABLE LOGININFO (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROVIDERID VARCHAR(255) NOT NULL,
  PROVIDERKEY VARCHAR(255) NOT NULL
);

CREATE TABLE USERLOGININFO (
  USERID VARCHAR(255) NOT NULL,
  LOGININFO BIGINT NOT NULL
);

CREATE TABLE PASSWORDINFO(
  HASHER VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  SALT VARCHAR(255),
  LOGININFO BIGINT NOT NULL
);

CREATE TABLE OAUTH1INFO(
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TOKEN VARCHAR(255) NOT NULL,
  SECRET VARCHAR(255) NOT NULL,
  LOGININFOID BIGINT NOT NULL
);

CREATE TABLE OAUTH2INFO(
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ACCESSTOKEN VARCHAR(255) NOT NULL,
  TOKENTYPE VARCHAR(255) NOT NULL,
  EXPIRESIN INTEGER,
  REFRESHTOKEN VARCHAR(255),
  LOGININFOID BIGINT NOT NULL
);

CREATE TABLE OPENIDINFO(
  ID VARCHAR(255) NOT NULL  PRIMARY KEY ,
  LOGININFOID BIGINT NOT NULL
);

CREATE TABLE OPENIDATTRIBUTES(
  ID VARCHAR(255) NOT NULL,
  KEYTYPE VARCHAR(255) NOT NULL,
  VALUETYPE VARCHAR(255) NOT NULL
);

CREATE TABLE PROJECT (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE TASK (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COLOR VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PROJECT INTEGER NOT NULL,
    FOREIGN KEY (PROJECT) REFERENCES PROJECT (ID)
);


CREATE TABLE MT_RESOURCE (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_KEY VARCHAR(255),
  RESOURCE_NAME VARCHAR(255)
);

CREATE TABLE MT_RESOURCE_DETAIL (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_TEXT VARCHAR(255),
  RESOURCE_LOCALE VARCHAR(255),
  RESOURCE_KEY INTEGER NOT NULL,
  FOREIGN KEY (RESOURCE_KEY) REFERENCES MT_RESOURCE (ID)
);
INSERT INTO MT_RESOURCE VALUES(1, 'default', '안녕하세요'), (2, 'default2', '윤창희 입니다.');

# --- !Downs
DROP TABLE TASK;
DROP TABLE PROJECT;
DROP TABLE MT_RESOURCE;
DROP TABLE MT_RESOURCE_DETAIL;
DROP TABLE USER;
DROP TABLE OPENIDATTRIBUTES;
DROP TABLE OPENIDINFO;
DROP TABLE OAUTH1INFO;
DROP TABLE OAUTH2INFO;
DROP TABLE PASSWORDINFO;
DROP TABLE USERLOGININFO;
DROP TABLE LOGININFO;
